name: vessel_map
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^1.0.8
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  intl: any
  loading_animation_widget: ^1.2.1
  pointer_interceptor: ^0.10.1+1
  provider: ^6.1.2
  universal_html: ^2.2.4
  websocket_universal: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
