services:
  db:
    restart: unless-stopped
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - database:/var/lib/mysql
  app:
    restart: on-failure
    depends_on:
      - db
    ports:
      - "3000:3000"
    build: .
volumes:
  database:
  images:
  djl-cache:
  