services:
  db:
    restart: on-failure
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql
  app:
    restart: on-failure
    depends_on:
      - db
    ports:
      - "${PORT}:3000"
    build:
      context: .
      args:
        PORT: ${PORT}
        HOST: ${HOST}
        APIKEY: ${APIKEY}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
  database:
  