services:
  app:
    ports:
      - "${PORT}:3000"
    build:
      context: .
      args:
        PORT: ${PORT}
        APIKEY: ${APIKEY}
    volumes:
      - database:/app/db
volumes:
  database:
  