services:
  app:
    ports:
      - "${PORT}:3000"
    build:
      context: .
      secrets:
        - apikey
    volumes:
      - database:/app/db
volumes:
  database:
secrets:
    apikey:
        environment: APIKEY
  